### PR TITLE
cart schema and routes

### PR DESCRIPTION
**Pull request by sarahedkins**
Issue #5

### CODE REVIEW

**Comment by codebyuma** [comment]
In server/db/models/cart.js, in the items array object, why do we need unit_price? It's already an attribute in the product model. Should we just have product and quantity in that object?

**Comment by codebyuma** [comment]
Don't forget error handlers in your routes :)

**Comment by png262** [comment]
unit_price is capturing the price of the product when it is added to the cart, doesn't necessarily tie to the unit_price in the Products model

**Comment by codebyuma** [comment]
In server/db/models/cart.js, would it be better to set specific values for status? I can't remember what workshop we did it in, but I thought we set possible values - so it can only be active, ordered, shipped or delivered.

**Comment by tiffanywang3** [comment]
When you're deleting, you should send a .status(204) right?

**Comment by png262** [comment]
added validation for possible values in Status field, and return status 204 in DELETE request

**Comment by codebyuma** [comment]
Approved!

**Comment by tiffanywang3** [comment]
Approved too!

**Pull request merged**
